### ISSUE TITLE
undefined reference to `vtable for RfalRfClass'

### ISSUE THREAD

**Issue by bluebaloon** [stm32duino/X-NUCLEO-NFC06A1#3]
I can compile the example code and it works good but when i try to debug the error stated below appears. I'm using PlatformIO ide with arduino framework. (ST STM32=17.1.0   ,   STM32duino X-NUCLEO-NFC06A1=1.0.1)

Linking .pio\build\nucleo_f401re\firmware.elf
c:/users/tpnbv/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/bin/ld.exe: warning: .pio/build/nucleo_f401re/firmware.elf has a LOAD segment with RWX permissions
c:/users/tpnbv/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/nucleo_f401re/lib840/libSTM32duino ST25R3916.a(rfal_rfst25r3916.cpp.o): in function `RfalRfST25R3916Class::RfalRfST25R3916Class(SPIClass*, int, int, unsigned long)':
C:\NUCLEO_F401RE\arduino_firmware\nucleo_nfc/.pio\libdeps\nucleo_f401re\STM32duino ST25R3916\src/rfal_rfst25r3916.cpp:55: undefined reference to `vtable for RfalRfClass'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\nucleo_f401re\firmware.elf] Error 1

**Comment by cparata** [comment]
Hello @bluebaloon ,
I have updated the NFC-RFAL library with a fix that should fix the linking issue. Could you try to download the 1.0.2 version and let me know if it solves your issue?
Best Regards,
Carlo

**Comment by bluebaloon** [comment]
Thanks, the problem is solved. Now i can debug. I have only changed the files that you have updated recenty (rfal_nfcDep.h, rfal_rf.h) and it worked. 

Thank you very much. 
Best regards.
